### ISSUE TITLE
Candidate: [MoneroGuy2] for MAGIC Monero Fund

### ISSUE THREAD

**Issue by jerryj123** [MAGICGrants/Monero-Fund#1]
Deleted above application.
Unfortunately I just took a new job which will not allow me to dedicate 12 hours per month.  So I need to drop out.  I remain a major supporter and am interested to see how I can help

**Comment by SamsungGalaxyPlayer** [comment]
@jerryj123 thanks for being our first ever committee candidate! Good luck!

Community members: feel free to ask questions and leave comments here, but be polite! Thank you!

**Comment by SeqBra** [comment]
cool

**Comment by SamsungGalaxyPlayer** [comment]
Please make sure to also [apply to be a voter](https://github.com/MAGICGrants/Monero-Fund#apply-to-be-a-fund-voter) @jerryj123! You are allowed to vote for yourself (which you should assume the other candidates will do).

**Comment by jerryj123** [comment]
Unfortunately I will need to withdraw.  I just took a new job and don't think I'd be able to allocate 12 or so hours per month.  Though I am more than happy to help were I can.

**Comment by SamsungGalaxyPlayer** [comment]
@jerryj123 okay, thank you for applying and your interest in Monero! Congratulations on the new job!
