### ISSUE TITLE
Candidate: [Name/Pseudonym] for MAGIC Monero Fund

### ISSUE THREAD

**Issue by Freeborz** [MAGICGrants/Monero-Fund#12]
- [ ] I have read and understand the [MAGIC Monero Fund documents](https://magicgrants.org/funds/monero/).
- [ ] I have read and understand the relevant [MAGIC Grants policies](https://magicgrants.org/about/documentation/).
- [ ] I understand that should I be in a position to receive funds from MAGIC Grants for any reason, I will need to provide identifying information to the organization privately. Election to a committee does not guarantee compensation even if compensation is made available, since MAGIC Grants has legal limitations on how it can disburse funds.
- [ ] I understand that an active committee is the number one factor in a Fund's success.
- [ ] I am at least 18 years old.

Replace this and the below text with approximately 5 paragraphs explaining:
* Why you are running for the committee
* Why you are a good candidate
* What experience you bring to the table (eg: fundraising)
* What you hope the Fund will accomplish while you are on the committee
* Contact information (optional)

Make sure to submit your application before the due date, and please campaign ethically in the community! Good luck, and thanks for applying!

**Comment by SamsungGalaxyPlayer** [comment]
Closing since no information was provided.
