### ISSUE TITLE
Candidate: whatgrindsmygear for MAGIC Monero Fund

### ISSUE THREAD

**Issue by whatgrindsmygear** [MAGICGrants/Monero-Fund#19]
- [x] I have read and understand the [MAGIC Monero Fund documents](https://magicgrants.org/funds/monero/).
- [x] I have read and understand the relevant [MAGIC Grants policies](https://magicgrants.org/about/documentation/).
- [x] I understand that should I be in a position to receive funds from MAGIC Grants for any reason, I will need to provide identifying information to the organization privately. Election to a committee does not guarantee compensation even if compensation is made available, since MAGIC Grants has legal limitations on how it can disburse funds.
- [x] I understand that an active committee is the number one factor in a Fund's success.
- [x] I am at least 18 years old.

* Why you are running for the committee
 I've been an active member of the crypto community since 2015, I believe crypto are the future and I want to be part of this revolution. Being part of the committee would allow me to give back to this amazing community, In 2017, I was part of the NEM community fund proposal for the travel by bit team (now travala), Having seen what importance the right funding has to a project, I would love to be part of the MAGIC fund committee to help funnel grants to the right recipients to really make a difference.

* Why you are a good candidate
100% of my free time is dedicated to crypto, I'm part of various channel and groups that aim at helping newcomers get a welcoming introduction to the crypto-world, I'm an advocate for privacy and freedom, Bitcoin and Monero are the closest thing human being have had to freedom since the beginning of time, for the first time in human history we can really take control of our belongings and Monero helps us having the privacy that we deserve.
* What experience you bring to the table (eg: fundraising)
With a background in operations, I could help the committee with weekly tasks and organizational-related matters to help streamline the process. I gained previous experience while working with the NEM community fund back in 2017 and I'm well versed with social media and digital platforms. I can manage online communities and help answer general queries that new candidates might have on the grants or crypto 
* What you hope the Fund will accomplish while you are on the committee
I hope the Fund will be able to grant funds to candidates that are really in need and that the funds granted can have a long term positive impact on the crypto community, 
* Contact information (optional)
Telegram ID: wrestlingspider
Email: wmpd@protonmail.com

**Comment by Rucknium** [comment]
Do you have a URL link to your work with NEM?
