### ISSUE TITLE
Candidate: [cryptpriv] for MAGIC Monero Fund

### ISSUE THREAD

**Issue by cryptpriv** [MAGICGrants/Monero-Fund#2]
- [x] I have read and understand the [MAGIC Monero Fund documents](https://magicgrants.org/funds/monero/).
- [x] I have read and understand the relevant [MAGIC Grants policies](https://magicgrants.org/about/documentation/).
- [x] I understand that should I be in a position to receive funds from MAGIC Grants for any reason, I will need to provide identifying information to the organization privately. Election to a committee does not guarantee compensation even if compensation is made available, since MAGIC Grants has legal limitations on how it can disburse funds.
- [x] I understand that an active committee is the number one factor in a Fund's success.
- [x] I am at least 18 years old.

Replace this and the below text with approximately 5 paragraphs explaining:
* Why you are running for the committee
I have been into crypto world since 10 years and into the cutting edge  software industry since 11+ years. I am very hopeful and strong believer of private cryptos, monero happens to be the biggest one and would want to help it become better and increase adoption worldwide. Being part of committee will allow me to contribute to this noble cause of helping private currencies.
* Why you are a good candidate
I am into high tech AI\ML space since 11+ years and have worked in principal positions in many of the fortune 10 tech companies and can lobby the use of monero to various tech giants. Due to privacy reasons cant divulge more information.

* What experience you bring to the table (eg: fundraising)
I have several contacts in the industry which can be leveraged for helping monero grow.
* What you hope the Fund will accomplish while you are on the committee
    - Increase adoption of monero
    - Review  and evaluate proposals 
    - Help in fund raising for proposals

**Comment by SamsungGalaxyPlayer** [comment]
Please make sure to also [apply to be a voter](https://github.com/MAGICGrants/Monero-Fund#apply-to-be-a-fund-voter) @cryptpriv! You are allowed to vote for yourself (which you should assume the other candidates will do).
