### ISSUE TITLE
[Grant] Peng Protocol

### ISSUE THREAD

**Issue by GenericMage** [MAGICGrants/Monero-Fund#23]
### To submit an application using this template, click [here](https://github.com/MAGICGrants/Monero-Fund/issues/new?assignees=&labels=&template=grant-application.md&title=[Grant+Title]) when logged in from a GitHub account.

For applications requesting greater discretion, please email MoneroFund@magicgrants.org with your submission yet note partial, and eventual full, disclosure of the your work (not your identity) will still occur.

# Candidate Background

* Majored in Psychology, possessing a good understanding of statistical analyses within the context of social sciences. 
* Worked alongside [Plebbit](https://github.com/plebbit) to design NFTs, and various other aspects of the overall protocol. 
* Did marketing and community management in Plebbit as well. 
* Assisted [Cheemsx](https://twitter.com/CheemsXmods) in creating NFTs, and in testing their novel secret NFT design and giving technical insight
* Other than that I have been involved in the management and design of many smaller projects operating in the BEP-20 blockchain, I have a firm grasp on the overall functioning of smart contracts and have deployed a few myself. 

# Project Description

Peng Protocol is a hybridization of decentralized payment networks (like Monero XMR), Peng Protocol works on top of existing infrastructure to create additional features to the blockchain without changing the base protocol. The network uses a peer-to-peer configuration called "hybrid line bus" which ensures that so long as there is even a single legitimate node; the network will continue to function. This allows extremely fast finality for creating things like NFTs, Fungible tokens, decentralized finance applications, all running alongside on-chain transactions and wallets. 

In the context of Monero XMR, Peng Protocol comprises of three main aspects; coded inputs, address abstraction, and hybrid networks. 
* Coded Inputs; a coded input is a fractional amount of XMR sent from an address made public to the network, this amount is issued by the webapp and acts as proof of ownership of a particular address. Example; x22j...lld0 *sends* 0.00000xxxxx03 XMR, after initiating it at the webapp, the amount is sent to an address owned by a node operator whose public key and public view key are known to the network. The network understands this sequence to mean that the user wants to transfer a certain amount of tokens within the "internal ledger" and thereby verifies that he/she is the legitimate owner of the address they are interacting with and that it was not initiated by accident. the "xxxxx" in the coded input is a random number required by the network to identify each transaction. 
* Address abstraction; Each address interacting with the webapp is a "pseudo-treasury" these are just wallets made public to the system through their public view key, users make use of a "login address" which is still private, its transactions are verified by sending to an already public address owned by a node operator. Address abstraction means that every public action can have an effect within the context of the internal ledger, for example user-A lists an NFT for sale, user-B initiates a purchase, user-B sends the required amount in XMR and the system updates the internal ledger to transfer the NFT to user-B, this is possible because both these addresses are public. 
* Hybrid networks: Hybrid networks or Hybrid line buses are peer-to-peer networks that have stratification based on which node is a parent or child, a parent is a node which is connected *to*, whereas a child is a node which is connected *from*. Each node on the network can only have (1) parent and (1) child, with exception of the root node which has no parent. The root acts as a form of authority, being able to remove nodes which do not act within consensus, this is called delinquency. Roots are held accountable by the formal website, which is an immutable object on IPFS, the formal website directs client-side requests to the oldest non-delinquent root with the longest chain, if a root acts outside consensus they are considered delinquent and all other nodes break away from them to attempt re-discovery. Roots can fall off and be replaced by the second node, when a former root returns it is now a child node without the same privileges. When a node besides the root falls off every node below it becomes cut-off from the network and assumes the oldest in their line is the new root, in this scenario node operators would need a robot to automatically check their node's connection in corroboration with the formal website and turn off the node, restarting it and using the latest non-delinquent root's IP address or hash.  
More graphical explanations of the overall protocol can be found [here](https://medium.com/@genericmage1127/pengv2a-monero-nfts-revised-aa2ce905182d?source=user_profile---------0----------------------------)   

# Technical Approach

The protocol requires multiple programming languages but overall is not something outside the scope of a socket and network programmer. The protocol would be implemented in three phases; first is implementing and testing the hybrid network without wallet functionalities, then second is adding said wallet functionalities and testing how the system copes with a high number of transactions and fixing any weaknesses or errors, third and final stage is open beta on testnet where users can critique some of our design choices or find bugs, this feedback would be used to finalize the project for mainnet after which it becomes immutable.  

# Milestones and Budget

First three (3) weeks 
* Find developers to implement the hybrid network without wallet functionalities, this will cost around $500-$1000 with an additional $4000 for stress-testing the network and purchasing hardware for a number of test nodes and self-hosting the immutable object on IPFS. 

Second two (2) weeks 
* Either work with the same developers from the previous installment or find Crypto friendly ones if the prior are unwilling or unable to create blockchain functionalities. Building the webapp on-top of the now existing network would cost between $1500-$3000, this includes testing and auditing. 

Final four (4) weeks 
* This will be the testnet phase, this period is particularly long so that we can get more of the community's insight into the network, there should not be significant costs in this phase as most development will just be bug-fixing or UI-UX changes. 

In total, developing the project would cost $8000.

**Comment by kayabaNerve** [comment]
The committee voted on February 14th (and privately communicated shortly after) against funding this grant. Thank you for your submission.
