### ISSUE TITLE
[Grant Application] Solve4Monero

### ISSUE THREAD

**Issue by Rucknium** [MAGICGrants/Monero-Fund#28]
<h3>general_fund</h3><p>true</p><h3>explore_page</h3><p>false</p><h3>project_name</h3><p>Solve4Monero</p><h3>your_name</h3><p>Muhammad Haruna </p><h3>email</h3><p>muhammadharunabala@gmail.com</p><h3>github</h3><p></p><h3>personal_github</h3><p></p><h3>other_contact</h3><p>twitter TechieAbba</p><h3>short_description</h3><p>Solve4monero Platform is an innovative online community-driven platform that aims to revolutionize knowledge-sharing and problem-solving. By harnessing the collective intelligence of its users, the  platform will facilitates the exchange of information, fosters collaboration, and rewards valuable contributions. Users from diverse backgrounds and expertise levels can engage with the platform, whether they seek answers to their questions or wish to share their knowledge with others. The platform operates on a decentralized model, leveraging blockchain technology to offer rewards in Monero cryptocurrency, ensuring transparency, security, and efficiency in transactions.
</p><h3>long_description</h3><p>Solve4monero Platform is an innovative online community-driven platform that aims to revolutionize knowledge-sharing and problem-solving. By harnessing the collective intelligence of its users, the  platform will facilitates the exchange of information, fosters collaboration, and rewards valuable contributions. Users from diverse backgrounds and expertise levels can engage with the platform, whether they seek answers to their questions or wish to share their knowledge with others. The platform operates on a decentralized model, leveraging blockchain technology to offer rewards in Monero cryptocurrency, ensuring transparency, security, and efficiency in transactions.

How it works..

On solve4monero you can ask questions, answer questions,  As answering questions involves receiving rewards paid in Monero (XMR) if the answer or solution provided is correct. And is selected by the user that give out that question.

Asking a question: Click "Create Task" to ask a question.

A suitable reward will incentivize others to invest their time and provide solution to your question or task .

Engaging in a task: This is synonymous with responding to a question. Once you commence working on a task, ensure promptness in initiating the solution process. There is no restriction on the number of users who can tackle a task, hence swift initiation guarantees timely submission of your solution. However, note that the countdown for solution time begins immediately after the task or question is posed.

 Here are some ways in which the Micro-Task (Solve4Monero)  Platform can benefit the Monero community, foster Monero adoption, and increase engagement:

1. Increased Monero Transactions:
By offering rewards in Monero cryptocurrency, the platform stimulates demand for Monero tokens, leading to increased transaction volume within the Monero ecosystem.
More users acquiring and transacting in Monero can contribute to the liquidity and overall value of the Monero network.

2. Exposure to Monero for New Users:
Users who participate in the platform may be introduced to Monero for the first time when they receive Monero rewards for their contributions.
This exposure can spark curiosity and interest in Monero, leading to further exploration and adoption of the cryptocurrency beyond the platform.

3. Educational Resources on Monero:
The platform can serve as an educational resource for Monero, providing users with information about its features, benefits, and use cases.
Users may learn about the importance of privacy and fungibility in cryptocurrency, which are core principles of Monero, thus increasing awareness and understanding of the Monero ecosystem.

4. Community Building and Engagement:
By integrating Monero rewards into the platform, the community becomes more tightly knit and engaged.
Users are incentivized to actively participate in discussions, contribute valuable content, and collaborate with others to earn Monero rewards, thereby fostering a vibrant and active community.

5.Monero Advocacy and Promotion:
The platform can serve as a platform for Monero advocacy and promotion, with users discussing the benefits of Monero and sharing their positive experiences with the cryptocurrency.
This grassroots advocacy can help attract new users to Monero and contribute to its wider adoption across various user demographics.

6.Integration with Monero Wallets and Services:
The platform can explore partnerships with Monero wallet providers and services to streamline the process of receiving Monero rewards.
Integration with Monero wallets could allow users to directly receive their rewards into their wallets, making the user experience seamless and convenient.

Progress:

At this stage of development, significant progress has been made on the Solve4monero platform. With the frontend nearing completion, users can soon expect a visually appealing and intuitive interface that enhances their overall experience. Additionally, the implementation of user authentication and authorization mechanisms lays a strong foundation for ensuring the security and integrity of user accounts and data. This crucial feature enables users to securely access the platform, manage their accounts, and engage with its functionalities with confidence. With these milestones achieved, the project is well-positioned to move forward.

</p><h3>free_open_source</h3><p>false</p><h3>are_you_lead</h3><p>true</p><h3>other_lead</h3><p></p><h3>potential_impact</h3><p>1. Increased Monero Transactions:
By offering rewards in Monero cryptocurrency, the platform stimulates demand for Monero tokens, leading to increased transaction volume within the Monero ecosystem.
More users acquiring and transacting in Monero can contribute to the liquidity and overall value of the Monero network.

2. Exposure to Monero for New Users:
Users who participate in the platform may be introduced to Monero for the first time when they receive Monero rewards for their contributions.
This exposure can spark curiosity and interest in Monero, leading to further exploration and adoption of the cryptocurrency beyond the platform.

3. Educational Resources on Monero:
The platform can serve as an educational resource for Monero, providing users with information about its features, benefits, and use cases.
Users may learn about the importance of privacy and fungibility in cryptocurrency, which are core principles of Monero, thus increasing awareness and understanding of the Monero ecosystem.

4. Community Building and Engagement:
By integrating Monero rewards into the platform, the community becomes more tightly knit and engaged.
Users are incentivized to actively participate in discussions, contribute valuable content, and collaborate with others to earn Monero rewards, thereby fostering a vibrant and active community.

5.Monero Advocacy and Promotion:
The platform can serve as a platform for Monero advocacy and promotion, with users discussing the benefits of Monero and sharing their positive experiences with the cryptocurrency.
This grassroots advocacy can help attract new users to Monero and contribute to its wider adoption across various user demographics.

6.Integration with Monero Wallets and Services:
The platform can explore partnerships with Monero wallet providers and services to streamline the process of receiving Monero rewards.
Integration with Monero wallets could allow users to directly receive their rewards into their wallets, making the user experience seamless and convenient.</p><h3>timelines</h3><p>what to do.
1. Monero Wallet Integration: Integration of a Monero wallet functionality allowing users to send, receive, and check balances of Monero cryptocurrency within the platform.

2. Updating the frontend design involves refining visual elements, layout, and user interface components to enhance user experience. This includes improving aesthetics, optimizing navigation, ensuring responsiveness across devices, and considering accessibility standards. Iterative design and usability testing are key for gathering feedback and making continuous improvements.

3.Performance and Security Optimization: Measures to optimize the platform's performance for efficient operation and enhance security protocols to safeguard user data and transactions.

4.Bug Identification and Resolution: Prompt identification and resolution of any bugs or issues that may arise during the development and testing phases to ensure smooth functioning of the platform.

5.Domain and Hosting Acquisition: Procurement of a domain name and hosting services to make the platform accessible on the internet.

6. marketing and online reach
</p><h3>proposed_budget</h3><p>The project milestone is to raise 50  XMR to complete building and integration by end June 2024

**Comment by Rucknium** [comment]
It seems there is a Kuno fundraiser for Solve4Monero too: https://kuno.anne.media/fundraiser/95ut/

**Comment by Cyrix126** [comment]
The idea has potential (allowing to incentive people answering questions) , but I have concerns:
From the biggest to smallest one:

> ####  free_open_source
> false

If it is not open source, we are funding private assets that could disappear tomorrow.
Why should the community fund this then ?

From what I understand, this service would be completely centralized when the same idea could _maybe_ work in p2p network. That would be a lot more interesting for the community and I think this option should be explored before funding a private business website. I admit I'm not the one who will propose a funding for this research right now, I suggest the author should investigate this path instead of this.
Even if not fully p2p, having the code of the website would be the minimum to have the guaranty that we would save this work if it is abandoned.  

> Users who participate in the platform may be introduced to Monero for the first time when they receive Monero rewards for their contributions.

They will discover it before. Because at the point they receive it, they should have already given an address. Except if the platform provide a custodial wallet, which would be again centralized.


> Solve4monero Platform is an innovative online community-driven platform 

 It will be used by the community, but because it is a private website, they have no real decision in the roadmap. So I don't think that you can say "community-driven" with this proposal.


> As answering questions involves receiving rewards paid in Monero (XMR) if the answer or solution provided is correct. And is selected by the user that give out that question.

Correct answer and selected answer can sometimes be something completely different.
What if the guy asking does not select the answer ? are the funds returned to them ? (situation: ah thanks for your answer, but I won't select it because I want my money back, sorry bro).


2 months seems very short. How do you know the time it will take to raise the 50xmr ? are you willing to work on your milestone before being funded ?


What would be your response if any on AI generated answers ?


> However, note that the countdown for solution time begins immediately after the task or question is posed.

What is the purpose of the countdown ?

**Comment by recanman** [comment]
The idea doesn't seem too potent honestly; it seems like a combination of StackExchange and [Monero Bounties](https://bounties.monero.social/). The proposal also reads like it was generated by an LLM, 

This project seems rather simple and it being closed-source is another glaring issue. If it were peer-to-peer (like @Cyrix126 mentioned), that would be more useful, as I believe developments around P2P markets over I2P or other anonymizing networks are very important (one example being [NeroShop](https://github.com/layters/testshop)).

**Comment by muhammadHarunaBala** [comment]
> It seems there is a Kuno fundraiser for Solve4Monero too: https://kuno.anne.media/fundraiser/95ut/

Yes, indeed, we attempted to launch the Kuno campaign last month before someone informed us about the grand application.

**Comment by muhammadHarunaBala** [comment]
> The idea has potential (allowing to incentive people answering questions) , but I have concerns: From the biggest to smallest one:
> 
> > #### free_open_source
> > false
> 
> If it is not open source, we are funding private assets that could disappear tomorrow. Why should the community fund this then ?
> 
> From what I understand, this service would be completely centralized when the same idea could _maybe_ work in p2p network. That would be a lot more interesting for the community and I think this option should be explored before funding a private business website. I admit I'm not the one who will propose a funding for this research right now, I suggest the author should investigate this path instead of this. Even if not fully p2p, having the code of the website would be the minimum to have the guaranty that we would save this work if it is abandoned.
> 
> > Users who participate in the platform may be introduced to Monero for the first time when they receive Monero rewards for their contributions.
> 
> They will discover it before. Because at the point they receive it, they should have already given an address. Except if the platform provide a custodial wallet, which would be again centralized.
> 
> > Solve4monero Platform is an innovative online community-driven platform
> 
> It will be used by the community, but because it is a private website, they have no real decision in the roadmap. So I don't think that you can say "community-driven" with this proposal.
> 
> > As answering questions involves receiving rewards paid in Monero (XMR) if the answer or solution provided is correct. And is selected by the user that give out that question.
Yes! 
> 
> Correct answer and selected answer can sometimes be something completely different. What if the guy asking does not select the answer ? are the funds returned to them? (situation: ah thanks for your answer, but I won't select it because I want my money back, sorry bro).
that's where dispute will come in,  we later reliased that,  you cannot setup atask without your account having the amount, an dit will not accessible again  till after resolutions. 
> 
> 2 months seems very short. How do you know the time it will take to raise the 50xmr ? are you willing to work on your milestone before being funded ?
... some part of the front end is done already, with much effort we can be able to come with something solid within that time. 
> 
> What would be your response if any on AI generated answers ?
> 
> > However, note that the countdown for solution time begins immediately after the task or question is posed.
yes of course .
> 
> What is the purpose of the countdown ?

 we are working on making the project public, and we are open to ideas that will reshape the platform in to something that will work for the community. and for the wallet our initial plan is to have custodial so that it will be easy for a first time user  crypto. but anyways we are open to ideas as i mentioned aboved.

**Comment by Cyrix126** [comment]
> we are working on making the project public

Does that means making the code open source and freely reusable ?

> we are open to ideas that will reshape the platform in to something that will work for the community.

Are you willing to search for a p2p solution ? In that case that would be awesome but would change drastically the work to do. I don't expect you to take this new route,  making it open source would already be much better.
For the questions I asked about how it works in some situations, It was not ideas but simply to know about which extent you thought about the difficulties you could encounter. Do you know how to solve those potential issues ?

> our initial plan is to have custodial so that it will be easy for a first time user crypto

Maybe a better way than letting all the funds on the platform (means more trust required) would be to take the approach of LocalMonero. You need to send funds when you are selling (here it would be when asking a question) and you need to put a receiving address when buying (here the user buy the xmr amount with 
his answer to the question).

**Comment by jwinterm** [comment]
I agree unless the code used to operate the website is fully open source (with the exception of maybe some deployment script or secret key represented by dummy value or something), then I am not sure this is appropriate to be funded via MAGIC.

**Comment by Rucknium** [comment]
@muhammadHarunaBala Thank you for your application. The five members of the Magic Monero Fund committee voted unanimously to reject this proposal. The main concerns of the committee members were about the lack of experience of the programmers involved, the fact that the open source license status of the project is unclear, and some members thought the proposal filled a niche that other projects already filled. We encourage you to get more involved in the Monero development community by, for example, joining the #monero-community-dev Matrix channel: https://matrix.to/#/#monero-community-dev:monero.social
