### ISSUE TITLE
Candidate: [Csilla Brimer] for MAGIC Monero Fund

### ISSUE THREAD

**Issue by csillabrimer** [MAGICGrants/Monero-Fund#3]
- [x ] I have read and understand the [MAGIC Monero Fund documents](https://magicgrants.org/funds/monero/).
- [ x] I have read and understand the relevant [MAGIC Grants policies](https://magicgrants.org/about/documentation/).
- [x ] I understand that should I be in a position to receive funds from MAGIC Grants for any reason, I will need to provide identifying information to the organization privately. Election to a committee does not guarantee compensation even if compensation is made available, since MAGIC Grants has legal limitations on how it can disburse funds.
- [x ] I understand that an active committee is the number one factor in a Fund's success.
- [ x] I am at least 18 years old.

Replace this and the below text with approximately 5 paragraphs explaining:
* Why you are running for the committee
I would like to contribute with educational materials and marketing towards the mission of Magic Grants
* Why you are a good candidate
It's in alignment with what I currently do and with my personal values and goal. We love covering what's happening within the Monero ecosystem, I love promoting Monero to local businesses, Universities and everyone around me.
* What experience you bring to the table (eg: fundraising)
I do have ideas about fundraising events we can host, marketing, partnerships, all things creative.
* What you hope the Fund will accomplish while you are on the committee
Short term probably help kids learn about this beautiful technology. Long term, I'm dying to be able to have a program that would onboard new Monero devs available for Universities
* Contact information (optional) cbrimer@willenrimer.com

Make sure to submit your application before the due date, and please campaign ethically in the community! Good luck, and thanks for applying!

**Comment by SamsungGalaxyPlayer** [comment]
Please make sure to also [apply to be a voter](https://github.com/MAGICGrants/Monero-Fund#apply-to-be-a-fund-voter) @csillabrimer! You are allowed to vote for yourself (which you should assume the other candidates will do).

**Comment by csillabrimer** [comment]
I'm not going to vote for myself lol
