### ISSUE TITLE
[Grant] XMR + Paga: Sovereign Business Infrastructure

### ISSUE THREAD

**Issue by tomholford** [MAGICGrants/Monero-Fund#32]
Hello Monero Fund team and community,

After submitting a grant proposal via email to the [MAGIC Monero Fund](https://monerofund.org/), the team asked me to create this Github issue to solicit community feedback.

Please see the *Executive Summary* below, or the full version here (PDF):
[xmr-paga-tnd-proposal.pdf](https://github.com/user-attachments/files/16199906/xmr-paga-tnd-proposal.pdf)

Please feel free to reply to this issue with any comments or questions you may have. 

Thank you for your time and consideration.

---

## Executive Summary

**True North Digital, S.A. de C.V.** ("True North Digital", "TND") (https://tnd.gg/) is a software research and development company that specializes in decentralized web applications and personal server technology. We are a team with over 25 combined years of experience and a passion for building products that empower people to take ownership of their data and finances.

At present, TND develops two primary product offerings: 

- **Paga**, a permissionless digital currency invoice service that enables businesses to accept digital currency payments with just a few lines of code while maintaining complete ownership over their customer and order data.
- **Tree**, a suite of personal server business tools, allowing merchants to operate with complete privacy and sovereignty. Key selling points are simple opt-in upgrades, minimal maintenance, Paga integration, and no base fees.

We are applying for a grant from the MAGIC Monero Fund to add support for XMR to our Paga invoice service. This will enable creators, merchants, and businesses to accept XMR as payment for their products and services, helping to grow the XMR ecosystem and bring decentralized finance to more people.

**Comment by XMRfamily** [comment]
We collect a flat 1% fee (up to $10) for each transaction facilitated by the Paga invoice service. Access to Tree's core functionality is free for all users. Premium features will be available for a monthly subscription. 

1% fee for invoice service?

**Comment by tomholford** [comment]
@XMRfamily Thanks for taking the time to read and ask a follow up question.

> 1% fee for invoice service?

Compared to credit card providers (typically $0.30 + 3% per transaction) or centralized crypto exchanges (spreads of 5% or more), 1% is one of the lowest in the online payments space. Also worth mentioning that the fee is capped at $10 per transaction. Considering that the Tree business software suite is free, it could be a significant operational improvement for many creators or business operators.

**Comment by XMRfamily** [comment]
.....maybe

**Comment by tomholford** [comment]
> .....maybe

@XMRfamily I'm open to feedback. What would an aligned incentive structure look like from your perspective?

**Comment by Rucknium** [comment]
@tomholford , all five members of the MAGIC Monero Fund committee (myself, kayabaNerve, monerobull, kowalabearhugs, and artlimber) voted to reject this proposal.

**Comment by tomholford** [comment]
> @tomholford , all five members of the MAGIC Monero Fund committee (myself, kayabaNerve, monerobull, kowalabearhugs, and artlimber) voted to reject this proposal.

@Rucknium understood, thank you for your time and consideration.
