### ISSUE TITLE
[Grant] Help me To Rebuild My Microgreens Business

### ISSUE THREAD

**Issue by Rucknium** [MAGICGrants/Monero-Fund#34]
# general_fund

true
# explore_page

true
# project_name

Help me To Rebuild My Microgreens Business
# your_name

Joanna
# email

[withheld]
# github

# personal_github

# other_contact

https://x.com/JHashmiye00 [more contact info witheld]
# short_description

Hello, I'm Joanna, a [age witheld] from [city witheld], Lebanon. After losing my job due to the closure of the microgreens store where I worked for two years, I'm now seeking support to open my own microgreens business. I need to raise $4000-$4200 to cover store rent, equipment, and materials. Any contribution, including cryptocurrency, will help me get back on my feet and create job opportunities for others affected by the conflict.
# long_description

Hello, my name is Joanna, a [age witheld] living in [city witheld], Lebanon. I live with my brother in the city, while my parents live in the mountains. For the past two years, I worked as a supervisor in a microgreens store. Unfortunately, due to the ongoing conflict between Israel and Lebanon, the owner decided to close the business and move to the United States. Along with my 20-25 fellow employees, I have been without work for the past three months. My Situation Being workless for three months has taken a toll on me. I am struggling to cover my basic living expenses. Every month, I need between $700 and $800 for house rent, utilities, medical expenses for my parents, and food. I have no savings left, and with only a few days left before rent is due, I’m in urgent need of support. My Goal My request is not just for immediate help with rent, but for a fresh start. I am determined to open my own microgreens store and create job opportunities for myself and some of my former colleagues who are also struggling. I have a strong customer base, and many of them are familiar with paying in cryptocurrency, so I plan to incorporate cryptocurrency payments into the business. What I Need To get the store up and running, I need to raise between $4000 and $4200. Here’s the breakdown: Store Rent $350 per month (I need to pay 3 months in advance, totaling $1050) Materials and Equipment $2500 for a refrigerator for herbs and other essential materials Wooden Work Tables $500 Your support will help me secure the store space, purchase the necessary materials, and begin production. This will not only support me, but will also help create jobs for others who are struggling in this difficult time. How You Can Help Any contribution, no matter how small, will bring me closer to my goal of reopening the microgreens store. Additionally, if you prefer, you can donate in cryptocurrency like Monero ,Bitcoin , ethereum , ect... Contact Information For more details, you can reach me at: X profile : https://x.com/JHashmiye00 [further contact info witheld] Thank you so much for your support in helping me rebuild and create opportunities for others.
# free_open_source

true
# are_you_lead

true
# other_lead

# potential_impact

This project is important to the Monero community because it demonstrates the practical use of cryptocurrency in real-world applications, particularly in regions like Lebanon where traditional financial systems may be less accessible. By accepting Monero, I can offer a privacy-focused payment option that aligns with the values of the Monero community. Supporting this project also helps to expand the adoption of Monero in everyday commerce, furthering its mission of decentralized and private transactions.
timelines

Month 1: Securing the Location - Secure funding and sign the lease for the microgreens store. - Pay the first three months' rent in advance. - Purchase initial equipment and materials (e.g., refrigerator, tables, seeds). **Month 2: Store Setup and Initial Production** - Set up the store and organize the workspace. - Begin planting the first batches of microgreens. - Finalize cryptocurrency payment system (Monero, Bitcoin, Ethereum) for customer transactions. **Month 3: Official Opening and Sales** - Launch the store and open for business. - Start selling microgreens to customers. - Begin marketing to expand the customer base, especially those who are interested in cryptocurrency payments. **Month 4-6: Growth and Community Outreach** - Expand production to meet growing customer demand. - Potentially hire 1-2 of my former colleagues to help with operations. - Continue accepting Monero and other cryptocurrencies, while promoting them to attract new customers in the community .
# proposed_budget

4300$
# bios

**Comment by kowalabearhugs** [comment]
All five members of the Magic Monero Fund committee (Rucknium, kayabaNerve, monerobull, artlimber, and myself) voted to reject this proposal. 

The applicant was encouraged to explore the options available through the [Kuno fundraising platform](https://kuno.anne.media/).
