### ISSUE TITLE
[Grant] Monerotopia Hackathon 2024

### ISSUE THREAD

**Issue by kowalabearhugs** [MAGICGrants/Monero-Fund#36]
# general_fund

true
# explore_page

false
# project_name

Monerotopia Hackathon 2024
# your_name

deverickapollo
# email

[withheld]
# github

https://github.com/deverickapollo/btcpayserver
# personal_github

https://github.com/deverickapollo
# other_contact

twitter: @deverickapollo
# short_description

I am proposing a review of BTCPay 2.0 to enhance Monero integration, culminating in a hackathon at Monerotopia in Mexico City. The project will focus on ensuring compatibility with the upcoming release of BTCPay 2.0 and integration issues, such as enabling remote node connections, UI improvements for managing monerod and monero-wallet-rpc, supporting multiple wallets per store, and allowing web-based wallet/key management. Funding will support the hackathon and development to streamline Monero usage within BTCPay.
# long_description

The goal of this project is to review BTCPay 2.0 and improve Monero integration to enhance usability for merchants and developers. This will be achieved by hosting a hackathon at Monerotopia in Mexico City, bringing together the Monero and BTCPay communities. The project will focus on addressing several key issues within BTCPay, including: 1. Connecting BTCPay to a remote Monero node. 2. Allowing custom commands for monerod and monero-wallet-rpc directly within the BTCPay UI. 3. Enabling the ability to update Monero software versions through the BTCPay user interface. 4. Supporting multiple Monero wallets per store, instead of limiting to one wallet per server. 5. Allowing users to replace Monero wallets or keys via a web interface, eliminating the need for command-line interaction. The hackathon will provide a collaborative environment to solve these challenges, with the goal of making Monero more accessible and functional within BTCPay. Funding will support the organization of the event, development resources, and community engagement to ensure the successful integration of Monero into BTCPay 2.0.
# free_open_source

true
# are_you_lead

true
# other_lead

# potential_impact

This project is crucial for the Monero community because it addresses key pain points that limit Monero’s integration into BTCPay, a widely-used open-source payment processor. As more merchants seek privacy-focused payment options, improving Monero’s functionality within BTCPay can significantly increase adoption. By solving issues such as remote node connections, better UI management of monerod and monero-wallet-rpc, multi-wallet support, and web-based wallet management, we will make Monero easier to use for merchants, developers, and end-users. These improvements not only enhance Monero’s usability in the real world but also strengthen its positioning as a viable, privacy-preserving option for global commerce. Hosting a hackathon to tackle these challenges will galvanize the Monero developer community, fostering collaboration and accelerating progress on much-needed features. This will ultimately empower users to have more control and flexibility in their Monero-based operations while expanding the reach of Monero in the broader cryptocurrency ecosystem.
timelines

Project Timeline: • October 1-7: • Milestone: Establish a group of developers. • Goal: Identify and onboard developers interested in improving Monero’s integration with BTCPay 2.0. • October 8-14: • Milestone: Set up communication and development infrastructure. • Goal: Create communication channels (e.g., Slack, Discord, etc.) and establish a development environment (e.g., GitHub repository, testing environments). • October 15-21: • Milestone: Reserve the location for hosting the hackathon. • Goal: Finalize logistics, including booking the space in Mexico City for the hackathon during Monerotopia (November 14-17). • October 22 - November 13: • Milestone: Review BTCPay 2.0 and test Monero integration. • Goal: Conduct an in-depth review of BTCPay 2.0, testing Monero’s current integration and identifying issues that need addressing during the hackathon. • November 14-17: • Milestone: Hackathon at Monerotopia. • Goal: Focus on developing solutions to key integration issues, including remote node connections, UI improvements, multi-wallet support, and web-based wallet/key management. • November 18-22: • Milestone: Post-hackathon evaluation and documentation. • Goal: Review the outcomes of the hackathon, consolidate code contributions, and document progress and future action items.
proposed_budget

1. Hackathon Logistics and Venue Costs – $700 • Details: This will cover the reservation of the space in Mexico City for the hackathon during Monerotopia, including any necessary equipment rentals, seating arrangements, and other venue-related expenses. 2. Developer Support and Materials – $400 • Details: This will include costs for providing developers with necessary materials (e.g., t-shirts, stickers, printed documentation, etc.), as well as any small stipends or food for developers participating in the hackathon. 3. Communication and Infrastructure Tools – $200 • Details: This covers the cost of setting up and maintaining development infrastructure, such as dedicated GitHub repositories, communication tools, and any additional software or hosting services required. 4. Post-Hackathon Documentation and Follow-Up – $200 • Details: This will fund the creation of detailed documentation on the integration improvements and outcomes from the hackathon, along with any post-event communication or content (e.g., reports, video summaries).
# bios

- Raspiblitz CI/CD pipelines designer - Maintainer of Monero on Umbrel - BTCPayserver contributor - 2023 Monerotopia workshop host

**Comment by kayabaNerve** [comment]
Superseded by #37
