### ISSUE TITLE
Candidate: [Twisted_Turtle] for MAGIC Monero Fund

### ISSUE THREAD

**Issue by Tw1sted-Turtle** [MAGICGrants/Monero-Fund#5]
- [X] I have read and understand the [MAGIC Monero Fund documents](https://magicgrants.org/funds/monero/).
- [X] I have read and understand the relevant [MAGIC Grants policies](https://magicgrants.org/about/documentation/).
- [X] I understand that should I be in a position to receive funds from MAGIC Grants for any reason, I will need to provide identifying information to the organization privately. Election to a committee does not guarantee compensation even if compensation is made available, since MAGIC Grants has legal limitations on how it can disburse funds.
- [X] I understand that an active committee is the number one factor in a Fund's success.
- [X] I am at least 18 years old.

* Why you are running for the committee

I'm running because I love Monero and believe my knowledge and skills would be useful on this committee. I've been an active member of the Monero community since the beginning and I'm always watching out for new opportunities to help the project. I'm not a great coder so my contributions thus far have mainly been education and art/graphics.

* Why you are a good candidate

I believe I'm a good candidate because this project is an intersection between many of my passions. I'm always up to speed on the latest developments in the community and I have experience with fundraising, graphic design, project management, basic web development, and education. 

* What experience you bring to the table (eg: fundraising)

I run the Monero Community Art fund (monerochan.art). I regularly coordinate with the community and work with many different artists to realize concepts that are voted on via Monero donations. I'm also fairly proficient with Photoshop and some of the Monero related memes and infographics I've created have been popular in some circles (e.g. The Citadel). 

I'm also experienced with educating newcomers on Monero from many different angles - technical, economical, and ideological - depending on what aspects interest them.

* What you hope the Fund will accomplish while you are on the committee

I hope to see the Fund succeed in spreading awareness and knowledge about Monero to more people who have a genuine use for it. I'd also like to see funding put towards more tools and resources that help enable less tech savvy individuals to understand and use Monero. 

* Contact information

Email:
tw1sted_turtle@protonmail.com

Matrix:
@twisted_turtle:matrix.org

**Comment by SamsungGalaxyPlayer** [comment]
Please make sure to also [apply to be a voter](https://github.com/MAGICGrants/Monero-Fund#apply-to-be-a-fund-voter) @Tw1sted-Turtle! You are allowed to vote for yourself (which you should assume the other candidates will do).
