### ISSUE TITLE
Candidate: [Vik Sharma] for MAGIC Monero Fund

### ISSUE THREAD

**Issue by CakeWallet** [MAGICGrants/Monero-Fund#6]
- [X] I have read and understand the [MAGIC Monero Fund documents](https://magicgrants.org/funds/monero/).
- [X] I have read and understand the relevant [MAGIC Grants policies](https://magicgrants.org/about/documentation/).
- [X] I understand that should I be in a position to receive funds from MAGIC Grants for any reason, I will need to provide identifying information to the organization privately. Election to a committee does not guarantee compensation even if compensation is made available, since MAGIC Grants has legal limitations on how it can disburse funds.
- [X] I understand that an active committee is the number one factor in a Fund's success.
- [X] I am at least 18 years old.

Replace this and the below text with approximately 5 paragraphs explaining:
* Why you are running for the committee:
I'm a proponent of granting funds to people/groups who are either needy or wanting to do something miraculous in the Monero ecosystem.
* Why you are a good candidate
I own and operate one of the if not the largest mobile wallet for monero on iOS and Android.  I also have 30 years of corporate experience ranging from C level to board member to entrepreneur.   I already fund initiatives in the Monero space personally and through Cake Wallet.
* What experience you bring to the table (eg: fundraising)
With the reach of Cake Wallet and myself, we can bring massive awareness to MAGIC Monero Fund. 
* What you hope the Fund will accomplish while you are on the committee
Accelerate the development of the Monero Ecosystem from not only the core development but also related projects.
* Contact information (optional)
vik@cakewallet.com

Make sure to submit your application before the due date, and please campaign ethically in the community! Good luck, and thanks for applying!

**Comment by SamsungGalaxyPlayer** [comment]
Please make sure to also [apply to be a voter](https://github.com/MAGICGrants/Monero-Fund#apply-to-be-a-fund-voter) @CakeWallet! You are allowed to vote for yourself (which you should assume the other candidates will do).
