### ISSUE TITLE
Candidate: [Rucknium] for MAGIC Monero Fund

### ISSUE THREAD

**Issue by Rucknium** [MAGICGrants/Monero-Fund#8]
- [x] I have read and understand the [MAGIC Monero Fund documents](https://magicgrants.org/funds/monero/).
- [x] I have read and understand the relevant [MAGIC Grants policies](https://magicgrants.org/about/documentation/).
- [x] I understand that should I be in a position to receive funds from MAGIC Grants for any reason, I will need to provide identifying information to the organization privately. Election to a committee does not guarantee compensation even if compensation is made available, since MAGIC Grants has legal limitations on how it can disburse funds.
- [x] I understand that an active committee is the number one factor in a Fund's success.
- [x] I am at least 18 years old.

### Why you are running for the committee

I am running because I would like to see more funding options for Monero research and development. The CCS is a good funding option for many people, but it doesn't work for everyone's life situation or preferences. Today Monero faces more threats than ever. Hopefully MAGIC can help the Monero Project confront and defeat those threats.

### Why you are a good candidate

I am a Monero Research Lab researcher and economist. With respect to Monero, my area of expertise is statistical obfuscation, which is a key part of Monero's privacy model. I expect that when evaluating funding proposals that my expertise will complement the expertise of members of the committee who may have knowledge in cryptography.

The committee members also have a responsibility to set the Fund's investment policy. For the purposes of the investment policy, I believe that the [Efficient-Market Hypothesis](https://en.wikipedia.org/wiki/Efficient-market_hypothesis) is approximately correct, and I would push for an investment policy that is risk-averse rather than one that attempts to "time" market highs and lows.

### What experience you bring to the table (eg: fundraising)

I have been funded through the CCS [to conduct critical research to improve Monero user privacy](https://ccs.getmonero.org/proposals/Rucknium-OSPEAD-Fortifying-Monero-Against-Statistical-Attack.html). This gives me experience in what is needed for developing a Monero research proposal and garnering community support and funds for it.

### What you hope the Fund will accomplish while you are on the committee

I hope that the Fund will help fund new and existing researchers to investigate [open research questions](https://github.com/monero-project/research-lab/issues/94) that are crucial for Monero's future. Having a stable funding source can provide an important ingredient for [recruiting more talent to the Monero Project](https://www.reddit.com/r/Monero/comments/pkg3d6/the_monero_project_should_actively_recruit/).

### Contact information (optional)

The best way to contact me is via Matrix: `@Rucknium:monero.social`

**Comment by SamsungGalaxyPlayer** [comment]
Please make sure to also [apply to be a voter](https://github.com/MAGICGrants/Monero-Fund#apply-to-be-a-fund-voter) @Rucknium! You are allowed to vote for yourself (which you should assume the other candidates will do).
